name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 🚨 IMPORTANT: Change 'main' to 'master' if your branch is named 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # 1. Inject the secret key using the robust line replacement method
      - name: Inject API Key
        # The 'c\' command means 'change the entire line'. We use double quotes 
        # for the run command to allow variable substitution of the secret.
        run: |
          sed -i '/VITE_GEMINI_API_KEY_PLACEHOLDER/c\const apiKey = "${{ secrets.GEMINI_API_KEY }}";' index.html
          
      # 2. Deploy the modified index.html to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          
 
