name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 🚨 IMPORTANT: Change 'main' to 'master' if your branch is named 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # This step sets a temporary environment variable for the deployment tool
      - name: Set API Key as Environment Variable
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # Use sed to inject a <script> block with the environment variable value 
          # directly into the <body>, making it available as window.GEMINI_API_KEY.
          sed -i '/<body /a <script>window.GEMINI_API_KEY = "'"$GEMINI_API_KEY"'";<\/script>' index.html
          
      # 2. Deploy the modified index.html to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          
 
