name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # 🚨 IMPORTANT: Change 'main' to 'master' if your branch is named 'master'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
  # 1. New, robust substitution using the 'awk' command
      - name: Inject API Key with awk
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          # The awk command finds the placeholder string and replaces it with the secret key.
          awk -v key="${{ secrets.GEMINI_API_KEY }}" '
            {
              gsub(/VITE_GEMINI_API_KEY_PLACEHOLDER/, key);
              print $0
            }
          ' index.html > temp_index.html && mv temp_index.html index.html
          
 
